### ISSUE TITLE
Doesn’t work on Travis CI (node 0.10.x), throws Unhandled rejection TypeError

### ISSUE THREAD

**Issue by jirutka** [jedmao/linez#13] opened 2015-07-30 17:37 UTC
```
$ eclint check $(git ls-files)
Unhandled rejection TypeError: Object # h has no method 'equals'
    at detectCharset (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/linez/js/linez.js:35:41)
    at linez (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/linez/js/linez.js:19:19)
    at /home/travis/.nvm/v0.10.36/lib/node_modules/eclint/js/eclint.js:69:27
    at tryCatcher (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/travis/.nvm/v0.10.36/lib/node_modules/eclint/node_modules/editorconfig/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:442:13)
```

Copied from https://github.com/jedmao/eclint/issues/30.

**Comment by jedmao** [comment] 2015-07-30 17:38
Can you submit a breaking "test"?

**Comment by jedmao** [comment] 2015-07-30 17:38
Because I am unable to reproduce this one.

**Comment by jirutka** [comment] 2015-07-30 18:22
Well, it’s extremely easy to reproduce this error. I’ve created example in [this repo](https://github.com/jirutka/eclint-fail) and you can see failed build [here](https://travis-ci.org/jirutka/eclint-fail/builds/73429114).

**Comment by jirutka** [comment] 2015-07-30 18:33
You have [8 failing tests](https://travis-ci.org/jedmao/linez/jobs/54685523) on 0.10.x, but since it’s badly configured, it exits with success, so you haven’t noticed that.

**Comment by jedmao** [comment] 2015-07-30 20:24
Thanks for pointing me in the right direction. Fixed in https://github.com/jedmao/linez/commit/3a769a5314cfd840f5c2fa859f75f27fd7a5bdb2 and https://github.com/jedmao/linez/commit/3a769a5314cfd840f5c2fa859f75f27fd7a5bdb2.

**Closed by jedmao** 2015-07-30 20:24 UTC

**Comment by jedmao** [comment] 2015-07-30 23:24
Real fix in https://github.com/jedmao/linez/commit/cfcbd035e0a4cb2013353ab0df225c9f7bf23bd3.
